export enum Keys {
  KEY_STORAGE_CONTACTS = 'PUpnFCC75Ls4AKgdeOc2QYfPj2mhUfiiCzzJG5BxKG/PwkJUx15CnvYUdqSu4ryS',
  KEY_STORAGE_PAPELERA = 'IQJkTIHgeKsIT4bfWVl3UAqhiiVJKjC5VfeCvD8zJuwocZaJXwNW3dRPUI98gN3N'
}
